resources:
- ../../base
patchesStrategicMerge:
- deployment_patch.yaml
- service_patch.yaml
- configmap_patch.yaml
namePrefix: production-
commonLabels:
  app: prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: jingfang/sbdemo
  newName: nginx:latest
#PatchesJson6902:
#- target:
#    version: v1
#    kind: Service
#    name: sbdemo
#  patch: |-
#    - op: replace
#      path: /spec/type
#      value: "ClusterIP"
namespace: prod
