apiVersion: v1
kind: Service
metadata:
  name: sbdemo
  namespace: default
  labels:
    app: sbdemo
spec:
  ports:
    - port: 8080
      name: sbdemo
  selector:
    app: sbdemo
  type: LoadBalancer
